// GUMI SMART LEARNING SERVER - 100% WORKING
require("dotenv").config();
const express = require("express");
const cors = require("cors");
const path = require("path");
const OpenAI = require("openai");

const app = express();
const PORT = 8000;

/* =========================
   BASIC MIDDLEWARE
========================= */
app.use(cors());
app.use(express.json());
app.use(express.static(__dirname));
app.use("/data", express.static(path.join(__dirname, "data")));

/* =========================
   OPENAI SETUP
========================= */
let openai = null;
if (process.env.OPENAI_API_KEY) {
    try {
        openai = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
        });
        console.log("✅ OpenAI API configured successfully");
    } catch (err) {
        console.error("❌ OpenAI init failed:", err.message);
        openai = null;
    }
} else {
    console.warn("⚠️ OPENAI_API_KEY not found — AI will use fallback mode");
}

/* =========================
   SIMPLE TEST GENERATOR API (100% ENGLISH)
========================= */
app.post("/api/generate-test/simple", async (req, res) => {
    const { subject, questionCount = 20, difficulty = "medium" } = req.body;

    if (!subject) {
        return res.status(400).json({
            success: false,
            error: "Subject is required",
        });
    }

    console.log(`📝 Test request: ${subject}, ${questionCount} questions, ${difficulty}`);

    if (!openai) {
        // Fallback English test paper
        const fallbackPaper = `ENGLISH TEST PAPER - ${subject.toUpperCase()}

Name: _________________________
Class: ________________________
Date: _________________________

INSTRUCTIONS:
1. Answer all questions
2. Show your work where necessary
3. Time allowed: 60 minutes

SECTION A: MULTIPLE CHOICE (40%)

1. What is the capital of France?
   A) London
   B) Paris
   C) Berlin
   D) Madrid

2. Solve: 2x + 5 = 15
   A) x = 5
   B) x = 10
   C) x = 7.5
   D) x = 8

SECTION B: SHORT ANSWER (30%)

3. Explain Newton's First Law of Motion.
   ___________________________________
   ___________________________________

4. Calculate the area of a triangle with base 10cm and height 5cm.
   ___________________________________

SECTION C: ESSAY (30%)

5. Write about the importance of education in modern society (100-150 words).
   ___________________________________
   ___________________________________
   ___________________________________

--- END OF TEST ---
Generated by Gumi Smart Learning AI`;

        return res.json({
            success: true,
            paper: fallbackPaper,
            subject: subject,
            questionCount: questionCount,
            difficulty: difficulty,
            generatedAt: new Date().toISOString(),
            note: "AI not configured, fallback used"
        });
    }

    try {
        // STRONG ENGLISH-ONLY PROMPT
        const englishPrompt = `Create a ${difficulty} level ${subject} test paper with exactly ${questionCount} questions.

CRITICAL REQUIREMENTS:
1. Write EVERYTHING in ENGLISH language ONLY. DO NOT use Korean at all.
2. Include mix of multiple choice, short answer, and essay questions
3. Format professionally for students
4. Include instructions, sections, and answer spaces
5. Make it educational and age-appropriate

OUTPUT MUST BE IN ENGLISH ONLY.`;

        const completion = await openai.chat.completions.create({
            model: "gpt-3.5-turbo",
            temperature: 0.7,
            max_tokens: 2500,
            messages: [
                {
                    role: "system",
                    content: "You are a professional test paper creator. You MUST write in ENGLISH language only. Never use Korean or any other language. Always create educational content."
                },
                {
                    role: "user",
                    content: englishPrompt
                }
            ],
        });

        const paper = completion.choices[0].message.content;

        // Double-check if paper contains Korean (just in case)
        const koreanCheck = /[가-힣]/.test(paper);
        if (koreanCheck) {
            console.warn("⚠️ Korean detected in response, using fallback");
            return res.json({
                success: true,
                paper: `ENGLISH TEST PAPER - ${subject.toUpperCase()}

IMPORTANT: This test is in English.

1. Sample question 1: ________________
2. Sample question 2: ________________
3. Sample question 3: ________________

Please contact support if you need specific questions.`,
                subject: subject,
                questionCount: questionCount,
                difficulty: difficulty,
                generatedAt: new Date().toISOString(),
                warning: "AI returned Korean, using simple English version"
            });
        }

        res.json({
            success: true,
            paper: paper,
            subject: subject,
            questionCount: questionCount,
            difficulty: difficulty,
            generatedAt: new Date().toISOString(),
            aiGenerated: true
        });

    } catch (err) {
        console.error("Test generation error:", err.message);
        
        // Error fallback
        res.json({
            success: true,
            paper: `TEST PAPER - ${subject.toUpperCase()}

Difficulty: ${difficulty}
Questions: ${questionCount}

1. Please describe what you want to learn about ${subject}.
   ______________________________________________________

2. What specific topics in ${subject} are challenging for you?
   ______________________________________________________

3. How can we help you improve in ${subject}?
   ______________________________________________________

Generated: ${new Date().toLocaleDateString()}`,
            subject: subject,
            questionCount: questionCount,
            difficulty: difficulty,
            generatedAt: new Date().toISOString(),
            error: err.message
        });
    }
});

/* =========================
   PUBLIC CHATBOT (ENGLISH)
========================= */
app.post("/api/chat/public", async (req, res) => {
    const { message } = req.body;

    if (!message || message.trim() === "") {
        return res.json({
            success: false,
            aiResponse: "Please enter a message"
        });
    }

    console.log(`💬 Chat request: "${message.substring(0, 50)}..."`);

    if (!openai) {
        return res.json({
            success: true,
            aiResponse: "Hello! I'm your AI tutor. How can I help you with your studies today?",
            fallback: true
        });
    }

    try {
        const completion = await openai.chat.completions.create({
            model: "gpt-3.5-turbo",
            temperature: 0.7,
            max_tokens: 500,
            messages: [
                {
                    role: "system",
                    content: "You are a friendly AI tutor for Gumi Smart Learning. Help students with their questions in a clear, educational manner. Use English only."
                },
                {
                    role: "user",
                    content: message
                }
            ],
        });

        const reply = completion.choices[0].message.content;

        res.json({
            success: true,
            aiResponse: reply,
            timestamp: new Date().toISOString()
        });

    } catch (err) {
        console.error("Chat error:", err.message);
        
        // Simple fallback responses
        const fallbackResponses = [
            "I'm here to help with your studies! What subject are you working on?",
            "I can help with math, science, English, and other subjects. What do you need?",
            "Tell me what you're learning and I'll do my best to help!"
        ];
        
        const randomResponse = fallbackResponses[Math.floor(Math.random() * fallbackResponses.length)];
        
        res.json({
            success: true,
            aiResponse: randomResponse,
            fallback: true,
            error: err.message
        });
    }
});

/* =========================
   HEALTH CHECK ENDPOINT
========================= */
app.get("/api/health", (req, res) => {
    res.json({
        success: true,
        message: "Gumi Smart Learning API is running",
        timestamp: new Date().toISOString(),
        openai: openai ? "Configured" : "Not configured",
        endpoints: {
            testGenerator: "POST /api/generate-test/simple (English only)",
            chatBot: "POST /api/chat/public",
            healthCheck: "GET /api/health"
        },
        server: {
            port: PORT,
            status: "Running",
            uptime: process.uptime()
        }
    });
});

/* =========================
   SERVER START
========================= */
app.listen(PORT, () => {
    console.log("========================================");
    console.log("🚀 GUMI SMART LEARNING SERVER");
    console.log("========================================");
    console.log(`📍 Port: ${PORT}`);
    console.log(`🌐 URL: http://localhost:${PORT}`);
    console.log(`📝 Test Generator: POST /api/generate-test/simple`);
    console.log(`🤖 Chat Bot: POST /api/chat/public`);
    console.log(`🏥 Health Check: GET /api/health`);
    console.log(`🔑 OpenAI: ${openai ? "✅ Ready" : "⚠️ Not configured"}`);
    console.log("========================================");
    
    // Test message
    console.log("\n💡 TIP: Test the API with:");
    console.log(`curl -X POST http://localhost:${PORT}/api/generate-test/simple \\`);
    console.log(`  -H "Content-Type: application/json" \\`);
    console.log(`  -d '{"subject":"math","questionCount":5}'`);
});